// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {networking} from '../models';

export function ListenC2Events(arg1:networking.SecureWebSocket):Promise<void>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Reconnect(arg1:string,arg2:string):Promise<void>;

export function Request(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<networking.Response>;
