// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1, arg2) {
  return window['go']['main']['App']['Download'](arg1, arg2);
}

export function DownloadToFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadToFile'](arg1, arg2, arg3);
}

export function ListenC2Events(arg1) {
  return window['go']['main']['App']['ListenC2Events'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Reconnect(arg1, arg2) {
  return window['go']['main']['App']['Reconnect'](arg1, arg2);
}

export function Request(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Request'](arg1, arg2, arg3, arg4);
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}
