api:
    host: 0.0.0.0
    port: 8080
operators:
    - username: anakin
      password: admin123
database_path: ../db/r2c2.db

# if doesn't exists will be generated automatically
jwt_secret: a6a3581fee9587e6fecc72175fb3eb7e35d64c77529a85542114c2e0f0483a53
